### ISSUE TITLE
error with feedback

### ISSUE THREAD

**Issue by SamDenys** [exporl/apex3#170] opened 2017-02-20 12:39 UTC
In an apex:constantProcedure experiment, adding <feedback length="2000">true</feedback> does not work (thumbs up/down are not shown). This **does** work in the experiment trainingprocedure.apx (examples>manual), even when changing the example to a constantProcedure experiment...
To prevent this problem, in our own experiment, we've added:         
<feedback_picture_positive>correct.png</feedback_picture_positive>
<feedback_picture_negative>wrong.png</feedback_picture_negative>
I put the figures in the images map I refer to in the experiment.

**Comment by Gundersanne** [comment] 2017-11-06 09:38
I can't reproduce this error. Do you still have the experiment?

Note that when not supplied with pictures, Apex will take default pictures (feedback_ok.png, feedback_nok.png) from the icons folder. If the icon folder got modified or moved Apex won't find them.

**Comment by mh21** [comment] 2017-11-07 14:46
I think this was an error in a helper function to resolve relative paths that got fixed a while ago, I think you can close it.

**Closed** 2017-11-09 11:39 UTC
